version: "3"

services:
  app:
    container_name: express-boilerplate
    restart: always
    build: .
    environment: 
      - PORT=8080
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongo:27017/mongo-db
    ports: 
      - "8080:8080"
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db

volumes:
  mongo-data: